use_frameworks!

target 'EFAutoScrollLabel_Example' do

    pod 'SnapKit', '~> 4.0.0'                   # AutoLayout

    pod 'EFAutoScrollLabel', :path => '../'

    target 'EFAutoScrollLabel_Tests' do
        inherit! :search_paths

        
    end
end
