platform :ios, '8.0'

use_frameworks!

target 'EFAutoScrollLabel_Example' do
    pod 'SnapKit', :git => 'https://github.com/alanzeino/SnapKit.git', :branch => 'xcode102'
    pod 'EFAutoScrollLabel', :path => '../'

    target 'EFAutoScrollLabel_Tests' do
        inherit! :search_paths

        
    end
end
